# This workflow will run a DVT on a schedule

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    cron: "0 * * * *

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: launch DVT
      run: python3 EHref_gfprobe_tet_rev3.py
