# This workflow will run a DVT on a schedule

name: Python Range DVT

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#   schedule:
#     - cron: "*/10 * * * *"
  # Allows manual triggering
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: checkout repo content
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.5
    - name: launch DVT
      run: |
        python3 EHref_gfprobe_tet_rev3.py
